create table cambio
(
    id                bigint generated by default as identity
        primary key,
    conversion_factor numeric(19, 2) not null,
    from_currency     varchar(3)     not null,
    to_currency       varchar(3)     not null
);
