create table book
(
    id          bigint generated by default as identity
        primary key,
    author      varchar(180)     not null,
    launch_date timestamp        not null,
    price       double precision not null,
    title       varchar(255)     not null
);
